### PR TITLE
Bug fixes

### LINKED ISSUE #6: Split-brain when redis master restarted without restart of its resec
Hello

I found a reproducible situation: when you stop redis process on master, it becomes red in consul, but resec do not removes it from redis-master service.
Then after redis process is restarted, healthcheck sets it to green, and we now have double master setup, with slave connected to one of them.
Restart of resec process on former master resolves issue.

resec's log output from this master:

```
2018/03/19 17:05:42 [ERROR] Can't connect to redis running on 127.0.0.1:6379
2018/03/19 17:05:42 [INFO] Redis HealthCheck changed to NOT healthy
2018/03/19 17:05:42 [INFO] Received update for master from consul
2018/03/19 17:05:42 [INFO] No redis master services in Consul
2018/03/19 17:05:42 [INFO] Received update for master from consul
2018/03/19 17:05:42 [INFO] Redis master updated in Consul
2018/03/19 17:05:42 [INFO] Received update for master from consul
2018/03/19 17:05:42 [INFO] No redis master services in Consul
2018/03/19 17:05:47 [INFO] Received update for master from consul
2018/03/19 17:05:47 [ERROR] Can't connect to redis running on 127.0.0.1:6379
2018/03/19 17:05:52 [INFO] Redis HealthCheck changed to healthy
2018/03/19 17:05:52 [INFO] Trying to acquire leader lock
2018/03/19 17:05:52 [INFO] Received update for master from consul
2018/03/19 17:05:52 [ERROR] Found more than one master registered in Consul

```

### LINKED ISSUE #18: enslavement should be retried (or don't talk to redis until its ready)
Saw this today in a Resec node, Redis was OOM killed and was restarted

```
2018/07/19 07:26:52 [INFO] Start!
2018/07/19 07:26:52 [INFO] Redis master updated in Consul
2018/07/19 07:26:57 [INFO] Redis status changed to healthy
2018/07/19 07:26:57 [ERROR] Could not enslave redis 10.0.157.245:6388 to be slave of 10.0.75.76:6388 (LOADING Redis is loading the dataset in memory)
```

Redis was still loading data from disk (~12 GB) when Resec tried to enslave it - this failed because redis wasn't ready to accept commands 

Resec did not retry enslavement, so the node never got enslaved and never registered in consul as a slave

### PR DESCRIPTION
**Pull request by jippi**
Fixes #6 
Fixes #18

### CODE REVIEW

File: redis.go [hunk 1]
```diff
@@ -42,25 +43,117 @@ func (rc *resec) runAsMaster() error {
...
+		log.Println("[DEBUG] Checking redis server info")
+
+		result, err := rc.redis.client.Info("server").Result()
+		if err != nil {
+			log.Printf("[WARN] Could not query for server info: %s", err)
+			connectionErrors++
+
+			if connectionErrors > allowedConnectionErrors {
+				log.Printf("[ERROR] Too many connection errors, shutting down")
+				rc.stopCh <- true
```
Comment (lorenzo) [inline redis.go]: Can you add a comment about this design decision? Something like "Cleaning up the internal state is too difficult at this point, better let a process monitor restart resec"

File: main.go [hunk 2]
```diff
@@ -12,13 +12,10 @@ func main() {
 		log.Fatal(err)
 	}
 
+	resec.waitForRedisToBeReady()
+	go resec.watchRedisUptime()
```
Comment (burdandrei) [inline main.go]: I thought about just adding this check in health check parser. They are using the same interval and both fired together, so what's the point to run it n the separate routine?

File: redis.go [hunk 3]
```diff
@@ -42,25 +43,117 @@ func (rc *resec) runAsMaster() error {
 
 // watchRedisReplicationStatus checks redis replication status
 func (rc *resec) watchRedisReplicationStatus() {
-	timer := time.NewTimer(rc.healthCheckInterval)
+	ticker := time.NewTicker(rc.healthCheckInterval)
```
Comment (burdandrei) [inline redis.go]: ticker is cooler than timer, but again we're waiting for `rc.healthCheckInterval` before start =(
